import { verifyWebhook } from '@clerk/nextjs/webhooks';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { NextRequest } from 'next/server';

// Lazily initialize Supabase client to avoid build-time errors
let supabaseClient: SupabaseClient | null = null;

function getSupabase(): SupabaseClient {
  if (!supabaseClient) {
    supabaseClient = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_KEY!
    );
  }
  return supabaseClient;
}

export async function POST(req: NextRequest) {
  try {
    // verifyWebhook handles signature verification using CLERK_WEBHOOK_SIGNING_SECRET
    const evt = await verifyWebhook(req);

    if (evt.type === 'user.created' || evt.type === 'user.updated') {
      const { id, email_addresses, first_name, last_name, image_url } = evt.data;
      const email = email_addresses[0]?.email_address;

      // Belt and suspenders: reject non-@oxy.so
      if (!email?.endsWith('@oxy.so')) {
        console.warn('[webhook] Rejected non-oxy.so user:', email);
        return new Response('OK', { status: 200 });
      }

      const fullName = [first_name, last_name].filter(Boolean).join(' ') || null;

      // Upsert by clerk_id. For new users, id is auto-generated by DB default.
      const { error } = await getSupabase()
        .from('user_profiles')
        .upsert(
          {
            clerk_id: id,
            email,
            full_name: fullName,
            avatar_url: image_url,
            updated_at: new Date().toISOString(),
          },
          { onConflict: 'clerk_id' }
        );

      if (error) {
        console.error('[webhook] Upsert failed:', error);
        return new Response('Database error', { status: 500 });
      }

      console.log(`[webhook] ${evt.type} synced:`, email);
    }

    return new Response('OK', { status: 200 });
  } catch (err) {
    console.error('[webhook] Verification failed:', err);
    return new Response('Invalid signature', { status: 400 });
  }
}
